### ISSUE TITLE
Docker method results in web server not finding templates

### ISSUE THREAD

**Issue by Jickelsen** [pstuifzand/ekster#28]
I've been trying to get Ekster working using [method 3](https://github.com/pstuifzand/ekster#method-3-using-docker--docker-compose) but when I visit the url for the Ekster web interface (the one mentioned [here](https://github.com/pstuifzand/ekster#when-ekster-is-running) but without the trailing /microsub) I get

`ERROR: open ./templates/base.html: no such file or directory`

It seems the web server is serving relative to the mounted directory /opt/microsub, the one containing backend.json. If I open a shell into the container and copy the template directory to this directory the web interface works.

(Just to double check, the url for the Ekster web interface, e.g. microsub.example.com, does not go into "me" in backend.json nor as "EKSTER_BASEURL" in docker-compose.ym, correct? I gathered both these should point to example.com)

**Comment by pstuifzand** [comment]
Thanks for trying Ekster!

I will check out the problem with the templates. It should work like described, or the description is wrong. I'll try to fix the one or the other.

The "me" value in `backend.json` should contain the URL of your homepage. Ekster will use it to check the token of the microsub readers and some other things.

`EKSTER_BASEURL` should point to the place where Ekster is served, from your example I would guess it will be `https://microsub.example.com/`.

**Comment by pstuifzand** [comment]
I created a new Docker image at `pstuifzand/ekster`. Could you try that? It should work.

**Comment by Jickelsen** [comment]
Seems I was using an old docker-compose file for some reason, from before [this commit](https://github.com/pstuifzand/ekster/commit/5b5b344f82bf25fa856de24558324feb32d559d6#diff-4e5e90c6228fd48698d074241c2ba760). No idea how that happened, must have been linked to from somewhere.

I'm not seeing any new images on Docker Hub. Using the current docker-compose file gives me
`ERROR: Cannot start service web: oci runtime error: container_linux.go:247: starting container process caused "exec:
 \"/app/eksterd\": stat /app/eksterd: no such file or directory" `

I was not getting this error using the old docker-compose.yml. Very strange!

**Comment by Jickelsen** [comment]
Sorry, I missed that the new docker image had a different name, without the d at the end. I tried pulling it but I get the same error as above. I'll have another go tomorrow and see if I can figure out what's causing the directories to be messed up

**Comment by pstuifzand** [comment]
I already found out that the problem occurs in the way the alpine image is
built. I'm not yet sure how this can be fixed. I need to do some more
research.

-- 
Peter Stuifzand | peterstuifzand.nl | @pstuifzand
<http://twitter.com/pstuifzand>

**Comment by pstuifzand** [comment]
@Jickelsen

What output do you get when you run. For me it shows the template files. What output do you get?

    docker run --entrypoint ls -e EKSTER_BASEURL=http://localhost:80/ -ti pstuifzand/ekster:alpine /app/templates

**Comment by pstuifzand** [comment]
I found the problem. The `docker-compose.yml` file in this repository contained a volume for the current directory. It was possible that it hid some files. I've also uploaded a new image to Docker Hub at `pstuifzand/ekster`.

If you would like to try again. It should work better now. You should at least get the new `docker-compose.yml` file and pull the new image.

**Comment by Jickelsen** [comment]
Seems you found it, I am not getting any template errors! Thank you
