### ISSUE TITLE
Hardcoded client_id breaks authentication

### ISSUE THREAD

**Issue by Jickelsen** [pstuifzand/ekster#29]
When trying to authenticate with a domain that uses Micro.blog as an [IndieAuth provider](https://help.micro.blog/2019/api-indieauth/) I get the error
`The redirect URL and client URL must use the same hostname.`
from Micro.blog instead of being redirected back to my own domain.

The url-encoded params are

`client_id=https%3A%2F%2Fp83.nl%2Fmicrosub-client`
`me=https%3A%2F%2Fmichelsen.se`
`redirect_uri=https%3A%2F%2Fmicrosub.michelsen.se%2Fsession%2Fcallback`

According to the [spec](https://www.w3.org/TR/indieauth/#redirect-url) the client_id and redirect_uri must indeed use the same hostname, unless the client_id url maintains a list of whitelisted domains. However, I see that client_id is hardcoded to https://p83.nl/microsub-client. I'm assuming this was done for a reason as there is a [specific commit](https://github.com/pstuifzand/ekster/commit/d8da433a6d53ece0cd6f591260ea540a28668983) dealing with this but I am not familiar enough with the IndieAuth authentication flow to be sure why.

**Comment by pstuifzand** [comment]
Thanks for the report. This makes sense. I will make the client_id equal to the EKSTER_BASEURL. That should do it.

It should be possible to use the microsub server without logging in on the frontend. It should be possible to use the server with something like Monocle or Together. Together has a way to preview and follow feeds in the frontend.

**Comment by pstuifzand** [comment]
I released a new version of the image to Docker Hub. I uses the specified baseurl as the clientID in the requests.

**Comment by Jickelsen** [comment]
That did it! Thanks for fixing this so quickly ✨
