### ISSUE TITLE
[Docker] Hitting save in web interface results in nginx throwing 405

### ISSUE THREAD

**Issue by Jickelsen** [pstuifzand/ekster#30]
When visiting EKSTER_BASEURL in a Docker setup, hitting Save in any of the channel settings results in an nginx 405 Not Allowed error.

**Comment by pstuifzand** [comment]
What do you have `EKSTER_BASEURL` set to? It should be a URL like `https://microsub.example.com/`.

**Comment by Jickelsen** [comment]
Yes, it's set to a full url, and the current settings work with IndieAuth on e.g. micro.blog.

**Comment by pstuifzand** [comment]
What do you get when you run `docker-compose logs -f web`? Is there an error message that shows when you click save?

**Comment by Jickelsen** [comment]
I don't seen any errors so it may be a misconfiguration on my end! I'll look further into it these coming days.

**Comment by pstuifzand** [comment]
Did you find the problem in the end? If you still need help with something, please let me know.
