### ISSUE TITLE
Can't parse time

### ISSUE THREAD

**Issue by Lohn** [pstuifzand/ekster#40]
I installed ekster today and got a lot of this messages on log

`ERROR: can't parse 2021-07-04T17:40:00+0100 as time`

The origin feed is the main feed of https://jvt.me

**Comment by pstuifzand** [comment]
Thank you for the report.

The time format that Ekster parses follows RFC3339, which expects the timezone offset `+0100` to use the format `+01:00`. The microformats page seems to use optional `:`. So perhaps this should be tried both ways.

**Comment by pstuifzand** [comment]
I pushed a fix for this: https://github.com/pstuifzand/ekster/commit/2f0758748dc2a9d9f2cf7a763810507a672fe04e
