### ISSUE TITLE
Use a different published port in docker-compose.yml

### ISSUE THREAD

**Issue by skpy** [pstuifzand/ekster#8]
When running this via `docker-compose`, it's quite possible that the host will already have something listening to TCP port 80, making the port declaration in `docker-compose.yml` not work as desired.

Maybe use `8000:80` or `8080:80` or something, instead?

**Comment by pstuifzand** [comment]
I think the docker-compose.yml should be viewed more as an example. It's not the docker-compose.yml file that I use, but it contains everything that you need to get started. I was already up to 8090 for my dev testing, so what the default should be, I don't know. I could add a way to add environment variables, so it's possible to set it from the outside, with the ".env" file.

**Comment by pstuifzand** [comment]
The latest docker-compose.yml file uses port 8089.
